CREATE DATABASE MI_API;

USE MI_API;

CREATE TABLE GAMES (
     ID_GAME            INT NOT NULL AUTO_INCREMENT,
     NAME_GAME          VARCHAR(30) NOT NULL,
     DESCRIPTION_GAME   VARCHAR(30) NOT NULL,
     PRIMARY KEY (ID_GAME)
);